# Site settings
title: Casa
email: mail@shyaamdeshmukh.com
description: "A boilerplate set up to create a bilingual Jekyll website by Wiredcraft."
keywords:
- Jekyll

# URL
url: "https://shyaam.github.io/jb-template"
baseurl: ""

# Google tracking (Analytics and Google Tag Manager)
# google_tag_manager: GTM-XXXXXX
# google_analytics: UA-XXXXXXX-X

# SEO
twitter: shyaam
facebook: https://www.facebook.com/shyaamdeshmukh
logo: /assets/logo.png
image: /assets/logo.png
social:
  - https://www.facebook.com/shyaamdeshmukh
  - https://twitter.com/shyaam
  - https://www.linkedin.com/in/shyaam
  - https://github.com/shyaam
  - https://weibo.com/xxxxxxxxxxxx/

# Sitemap (see sitemap.xml)
sitemap:
  changefreq: weekly

# Build settings
exclude: ['README.md', 'Makefile']

# Collections
permalink: /:categories/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      class: post
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
      class: post

# Plugins
plugins:
- jekyll-sitemap

# Multiligual
lang:
  - en
  - fr
  - zh

# Version (helps with force reloading assets)
version: sparkle

# Jekyll+ (not useful if you're running on GitHub pages)
# jekyllplus: Wiredcraft/jekyll-basics/master
